version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todo_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user123
      MYSQL_PASSWORD: todo_pass123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
